### ISSUE TITLE
Old benchmark results missing from dashboard

### ISSUE THREAD

**Issue by jc-harrison** [Flowminder/FlowKit-benchmarks#10]
FlowMachine queries which previously accepted a `level` argument now take a `spatial_unit` instead, and the benchmarks have been updated to reflect this. In doing so, the `level` benchmark parameters have also changed name to `spatial_unit`, and as a result the benchmark results with the old `level` parameters no longer show up in the plots on the dashboard. The results are all still present in the repo, so it would be good to get these to appear again on the plots.

**Comment by greenape** [comment]
Need to explicitly version the benchmarks to get them to persist when the code changes?

**Comment by jc-harrison** [comment]
They're all explicitly versioned already, so that's not the problem. I think it's because the "params" or "param_names" in the old results files don't align with those listed in `benchmarks.json`, so ASV doesn't know how to label them.

**Comment by jc-harrison** [comment]
I temporarily fixed this by manually adding additional parameter values to `benchmarks.json`, but `benchmarks.json` is automatically recreated when new benchmarks are run, so my changes were overwritten.

**Comment by jc-harrison** [comment]
One solution would be to go through all of the old results files and change the values of the `level` parameters to match those of the new `spatial_unit` parameters.
