### ISSUE TITLE
Add benchmarks for dfs metrics

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit-benchmarks#7]
DFS metrics are available via the API and hence need a benchmark

**Comment by maxalbert** [comment]
@jch1g10 I wasn’t aware we have benchmarks for these already. Did you any, or was this closed inadvertently?

**Comment by jc-harrison** [comment]
We have benchmarks for `DFSTotalMetricAmount` (have done for about a month, but I forgot to close the issue).
